version: "3.9"

services:
  back:
    container_name: oauth2-back
    build: .
    ports: [ "8520:4512" ]
    volumes:
      - .:/home/app/project
    tty: true
    depends_on:
      - db
  db:
    image: postgres:15.1-alpine
    restart: always
    container_name: oauth2-db
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
